### ISSUE TITLE
Images Module does not process images [$5 awarded]

### ISSUE THREAD

**Issue by OstlerDev** [OstlerDev/PopcornTV-App#8]
```
error: uncaughtException: Can't load the addon. Issue to: https://github.com/zhangyuanwei/node-images/issues 
{ date: 'Sat Jul 25 2015 16:43:53 GMT-0600 (MDT)',
  process: 
   { pid: 41063,
     uid: 0,
     gid: 0,
     cwd: '/Users/sky/Desktop/PopcornTV-App',
     execPath: '/usr/local/lib/node_modules/electron-prebuilt/dist/Electron.app/Contents/MacOS/Electron',
     version: 'v2.3.1',
     argv: 
      [ '/usr/local/lib/node_modules/electron-prebuilt/dist/Electron.app/Contents/MacOS/Electron',
        '.' ],
     memoryUsage: { rss: 126259200, heapTotal: 36365016, heapUsed: 28467224 } },
  os: 
   { loadavg: [ 1.66796875, 1.94091796875, 1.88916015625 ],
     uptime: 181494 },
  trace: 
   [ { column: 7,
       file: '/Users/sky/Desktop/PopcornTV-App/app/node_modules/images/binding.js',
       function: '',
       line: 61,
       method: null,
       native: false },
     { column: 26,
       file: 'module.js',
       function: 'Module._compile',
       line: 428,
       method: '_compile',
       native: false },
     { column: 10,
       file: 'module.js',
       function: 'Object.Module._extensions..js',
       line: 446,
       method: 'Module._extensions..js',
       native: false },
     { column: 32,
       file: 'module.js',
       function: 'Module.load',
       line: 353,
       method: 'load',
       native: false },
     { column: 12,
       file: 'module.js',
       function: 'Function.Module._load',
       line: 308,
       method: 'Module._load',
       native: false },
     { column: 17,
       file: 'module.js',
       function: 'Module.require',
       line: 363,
       method: 'require',
       native: false },
     { column: 17,
       file: 'module.js',
       function: 'require',
       line: 382,
       method: null,
       native: false },
     { column: 15,
       file: '/Users/sky/Desktop/PopcornTV-App/app/node_modules/images/index.js',
       function: '',
       line: 4,
       method: null,
       native: false },
     { column: 26,
       file: 'module.js',
       function: 'Module._compile',
       line: 428,
       method: '_compile',
       native: false },
     { column: 10,
       file: 'module.js',
       function: 'Object.Module._extensions..js',
       line: 446,
       method: 'Module._extensions..js',
       native: false } ],
  stack: 
   [ 'Error: Can\'t load the addon. Issue to: https://github.com/zhangyuanwei/node-images/issues',
     '    at Object.<anonymous> (/Users/sky/Desktop/PopcornTV-App/app/node_modules/images/binding.js:61:7)',
     '    at Module._compile (module.js:428:26)',
     '    at Object.Module._extensions..js (module.js:446:10)',
     '    at Module.load (module.js:353:32)',
     '    at Function.Module._load (module.js:308:12)',
     '    at Module.require (module.js:363:17)',
     '    at require (module.js:382:17)',
     '    at Object.<anonymous> (/Users/sky/Desktop/PopcornTV-App/app/node_modules/images/index.js:4:15)',
     '    at Module._compile (module.js:428:26)',
     '    at Object.Module._extensions..js (module.js:446:10)' ] }
```
##

**Comment by OstlerDev** [comment]
Looks like this is happening because of this line: https://github.com/zhangyuanwei/node-images/blob/master/binding.js#L48

Inside the project running that produces "2.3.1" however, it produces "0.12.2" when run directly from node.

Looks like an issue with Electron.

**Comment by OstlerDev** [comment]
Electron uses iojs instead of node, thus creating the issue. We could actually use this to our advantage by not forcing the user to download and install nodejs but rather use the built in iojs that is shipped with it to install the npm packages.

**Comment by OstlerDev** [comment]
I either need to implement some way into PopcornTV directly, or get this fixed with a working pull request.

May end up making an organization then forking node-images and making the needed modifications.

**Comment by OstlerDev** [comment]
Fixed with #16

**Comment by OstlerDev** [comment]
Welp, turns out that #16 did not fix it.

**Comment by OstlerDev** [comment]
Fixed using a custom node module. https://github.com/PopcornTV/node-images
